import { createSlice } from '@reduxjs/toolkit';


const initialState = {
    productDetails: {
        name: '',
        description: '',
        price: '',
        qte: '',
    }
};

export const productsSlice = createSlice({
    name: 'products',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setname: (state, action) => {
            state.productDetails.name = action.payload.name
        },
        setdescription: (state, action) => {
            state.productDetails.description = action.payload.description
        },
        setprice: (state, action) => {
            state.productDetails.price = action.payload.price
        },
        setqte: (state, action) => {
            state.productDetails.qte = action.payload.qte
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },
});

export const { setname, setdescription, setprice, setqte } = productsSlice.actions;

export default productsSlice.reducer;